### ISSUE TITLE
JENKINS/Python3 - Add Python3 to the ssh-slave dockerfile

### ISSUE THREAD

**Issue by sdonovan1985** [atlanticwave-sdx/atlanticwave-proto#121]
https://github.com/atlanticwave-sdx/atlanticwave-proto/blob/master/testing/testing-infrastructure/jenkins-ssh-slave-modification/Dockerfile

For Python3 testing, we need a Python3 environment. Easy, single line change.

**Comment by YufengXin** [comment]
solved
