### ISSUE TITLE
Python3 - Steiner Tree lib replacement with NetworkX

### ISSUE THREAD

**Issue by sdonovan1985** [atlanticwave-sdx/atlanticwave-proto#125]
In 2.x of networkx, there's a [Steiner Tree](https://networkx.github.io/documentation/stable/reference/algorithms/approximation.html#module-networkx.algorithms.approximation.steinertree) approximation method. We've been using version 1.11 thus far. 

There is a [migration guide](https://networkx.github.io/documentation/stable/release/migration_guide_from_1.x_to_2.0.html), and I'm definitely seeing some of these errors.

**Comment by YufengXin** [comment]
Replaced by #154
