### ISSUE TITLE
Authentication work

### ISSUE THREAD

**Issue by sdonovan1985** [atlanticwave-sdx/atlanticwave-proto#130]
Authentication was worked on by Ankita a couple of years ago, and her approach turns out to the spot on. Shibboleth is the go-to authentication platform that's being used around the world, and needs to be fully integrated. Right now, there is shibboleth code in the master branch, but it's turned off by default. 

I have not tested it, but I know that it needed some configuration work done (to be a trusted endpoint mostly) before it'll work.

**Comment by YufengXin** [comment]
Merged into new issue #164
