### ISSUE TITLE
L2MP rate limiting

### ISSUE THREAD

**Issue by YufengXin** [atlanticwave-sdx/atlanticwave-proto#137]
Manual configuration with a new L2VPN VFC is validated by Mert.
Code modification is on the way.

**Comment by mcevik0** [comment]
Code changes are committed to [l2mp-ratelimiting](/atlanticwave-sdx/atlanticwave-proto/tree/l2mp-ratelimiting) branch . 

Problem reported on #147 is relevant. Work is in progress, l2mp ratelimiting changes will be merged after this work.

**Comment by mcevik0** [comment]
Changes are implemented in https://github.com/atlanticwave-sdx/atlanticwave-proto/commit/860e7c4562c86dd365af76d1bb0eca55a5381a41 
Tested and works well.

**Comment by YufengXin** [comment]
[https://github.com/atlanticwave-sdx/atlanticwave-proto/commit/32d2731a5722f39a38bd1d5cd0f23a93d5138717]
added a log and peaceful return in removal of L2MPRateLimiting when not Corsa switches.
