### ISSUE TITLE
Specify Corsa case for creating/deleting ratelimiting tunnels in LocalController.py

### ISSUE THREAD

**Issue by mcevik0** [atlanticwave-sdx/atlanticwave-proto#149]
Move L2MP ratelimiting tunnel create/delete in a condition statement for Corsa case. Currrent code breaks when `corsaratelimitbridgel2mp` key is not included in mininet manifest.

```
File "LocalController.py", line 653, in remove_l2mp_ratelimiting_tunnel
  bridge_ratelimit_l2mp = internal_config['corsaratelimitbridgel2mp']
KeyError: 'corsaratelimitbridgel2mp'
```

https://renci.slack.com/archives/GT8K0Q19P/p1586217619038400

**Comment by mcevik0** [comment]
This will be done once the major changes are merged in the code. At this moment, I suggest adding the necessary keys to the mininet manifests.

**Comment by mcevik0** [comment]
I just recognized @YufengXin 's comment on this 
https://github.com/atlanticwave-sdx/atlanticwave-proto/issues/137#issuecomment-612154155
that already addressed the issue.

**Comment by YufengXin** [comment]
fixed
