### ISSUE TITLE
Bandwidth requests for L2 tunnels in kbps or B/s?

### ISSUE THREAD

**Issue by JoaquinChung** [atlanticwave-sdx/atlanticwave-proto#25]
I wanted to make an L2 tunnel of 100Mbps on my testbed, so I requested 12,500,000 B/s on the AWave/SDX web portal. However, what I see on the rate limiting switch is the following:

  committed info rate (kbps) : 12500000
  committed burst size (KB)  : 16646144
  excess info rate (kbps)    : 12500000
  excess burst size (KB)     : 262144
 
I think this is the last change made on the HTML max bandwidth on joaquinthesis branch. I think the master branch should be correct, but instead of asking for B/s in the web portal, it should ask for kbps. Unless a division by 8 is missing somewhere.

**Comment by sdonovan1985** [comment]
This is also a bug. There's inconsistency, as I noted in #32. Tagging with Bug now. I'm working on fixing this in the https://github.com/atlanticwave-sdx/atlanticwave-proto/tree/sdxrulesdev branch, as it's the current dev branch.

**Comment by sdonovan1985** [comment]
Note from DP2000 Configuration guide, for version 3.0: CIR and EIR are in kbits/sec, CBS and EBS are kbytes

So, that's what's at the end.

https://github.com/atlanticwave-sdx/atlanticwave-proto/blob/sdxrulesdev/localctlr/RyuTranslateInterface.py#L474 - Where rule is installed.
https://github.com/atlanticwave-sdx/atlanticwave-proto/blob/sdxrulesdev/shared/VlanTunnelLCRule.py#L61 - BW in the LCRule
https://github.com/atlanticwave-sdx/atlanticwave-proto/blob/sdxrulesdev/shared/L2TunnelPolicy.py#L250 - BW in the Policy
https://github.com/atlanticwave-sdx/atlanticwave-proto/blob/sdxrulesdev/sdxctlr/RestAPI.py#L340 - BW at the API

So, the bandwidth number is taken directly from the form.

This means that the form needs to be updated to:

1. Accept something that's translated to kbit/sec.
2. Have a sane rules checking going on.
3. Tell users what they're entering in.

The operator form is here: https://github.com/atlanticwave-sdx/atlanticwave-proto/blob/sdxrulesdev/sdxctlr/templates/index.html#L133

The scientist form is here: https://github.com/atlanticwave-sdx/atlanticwave-proto/blob/sdxrulesdev/sdxctlr/templates/index.html#L181
BUT it's not useful, as there's some processing that occurs here: https://github.com/atlanticwave-sdx/atlanticwave-proto/blob/sdxrulesdev/sdxctlr/RestAPI.py#L350

So, second translation goes on here:
https://github.com/atlanticwave-sdx/atlanticwave-proto/blob/sdxrulesdev/shared/EndpointConnectionPolicy.py#L110

This DOES NOT have proper bit-byte translation going on... so in addition to the changes to the template/index.html file, we also need to change shared/EndpointConnectionPolicy.py.

Not terrible...

**Comment by sdonovan1985** [comment]
Should be fixed. Not tested, but this was primarily a documentation change. Closing.
