### ISSUE TITLE
Finish Documentation for REST API

### ISSUE THREAD

**Issue by sdonovan1985** [atlanticwave-sdx/atlanticwave-proto#40]
The [REST API Overhaul Documentation](https://docs.google.com/document/d/1yCbCZYFwVfDbKzIxoKz9zuhJitZVomA2aWUtsgsP7rw/edit?usp=sharing) needs to be finished and sent around for others to review.

Current status:
- GET and POST definitions have been created
- User roles need to be defined
- PUT operations need to be defined
- DELETE operations need to be defined
- Fix the FIXMEs scattered about the document
- Table of Contents needs to be created

**Comment by sdonovan1985** [comment]
I've made major updates to the document. 

That said, there are a number  of "FIXMEs" mostly related to how to handle filtering, and what user information actually looks like. Not going to close this one now, but below is a link to the current version of the document.

[AtlanticWave%2FSDX REST API Rework - 2017 October.pdf](https://github.com/atlanticwave-sdx/atlanticwave-proto/files/1415260/AtlanticWave.2FSDX.REST.API.Rework.-.2017.October.pdf)

**Comment by sdonovan1985** [comment]
Joaquin wanted #26 integrated into the new REST API. Do include that.

**Comment by sdonovan1985** [comment]
[REST Overhaul 2Nov2017.pdf](https://github.com/atlanticwave-sdx/atlanticwave-proto/files/1438894/REST.Overhaul.2Nov2017.pdf)

Updated document, includes documentation for #26. @JoaquinChung Please review change on page 12 and 13.

**Comment by JoaquinChung** [comment]
Pages 12 and 13 look very good

**Comment by sdonovan1985** [comment]
Waiting to hear what the FIU-associated developers in Brazil think before closing this. There are some holes, but that will become evident when implementing.

**Comment by sdonovan1985** [comment]
Updated based on the most recent changes in #43.

**Comment by sdonovan1985** [comment]
[AtlanticWave%2FSDX REST API Rework - 2017 November.pdf](https://github.com/atlanticwave-sdx/atlanticwave-proto/files/1492345/AtlanticWave.2FSDX.REST.API.Rework.-.2017.November.pdf)

This is the newest version.

**Comment by sdonovan1985** [comment]
Closing this. There hasn't been any updates in over a year.
